DROP TABLE "GCG_4559_PO_CONFCHK" IN DICTIONARY;
CREATE TABLE "GCG_4559_PO_CONFCHK"("PURCHASE_ORDER" CHAR(7),"CONF" CHAR(1),"GS_USER" CHAR(8),"DATE_CONF" DATE);
CREATE INDEX "GCG_4559POCONFCHK00" ON "GCG_4559_PO_CONFCHK"("PURCHASE_ORDER" ASC);